### ISSUE TITLE
Do we need ClickSVN?

### ISSUE THREAD

**Issue by KeyC0de** [TanninOne/modorganizer-umbrella#41]
If we have git is it required to have Subversion too? What does SVN provide additionally?

**Comment by LePresidente** [comment]
I'm not sure, you can comment out https://github.com/TanninOne/modorganizer-umbrella/blob/bddf30e57836c45c8b6bc61422638e82b377bbde/config.py#L122

and see if any fetches fail.

**Comment by KeyC0de** [comment]
So i run it with python 2. Code is written in python2. It downloaded approximately 2.2GB of various programs.. And Python folder alone is 356MB. It built a lot of them, but ended with an error that "building usvfs 32bit dll failed". 

What is this? I have downloaded CMake projects before. Why didn't you just create a cmakeLists to have everything you need built. What do we accomplish with this. I have a bunch of programs now, most i don't need and i don't see the mod organizer files anywhere.. 

I love your work, but what does this repository do? MO is really a great program and I want to help in its development. What can i do? Would it be better if i just downloaded every MO project individually with Visual Studio 2015 and build each one separately? Is it possible? Asking for some clarifications. Thanks in advance.

**Comment by TanninOne** [comment]
MO2 has a ton of dependencies (qt5, python, pyqt, boost, to name just a few) that need to be built from source. I've attached the dependency/build step graph for fun and giggles.
You _could_ probably build this with a single cmake project but I didn't manage it back then and the cmake files were far more complicated than this python program.
You can of course build each subproject individually but you'd still have to build all the dependencies if you want to build the whole project.

![graph](https://user-images.githubusercontent.com/8525754/30066468-44f7fbbc-9258-11e7-87f7-f7c85c4474d4.png)

**Comment by KeyC0de** [comment]
So ever since you responded i've been trying to just build the modorganizer project. I haven't got around how to install QTDeclarative plugin. I can't find it anywhere. I posted on Qt support forum about it [here](https://forum.qt.io/topic/83012/how-to-create-qtdeclarative-plugin-library). You can check out all about my progress there. I imagine that this was something that occurred with you and you couldn't build it back then? Well this is the last chance. If they don't answer how to get QtDeclarative thing i won't build the project and i quit.

**Comment by KeyC0de** [comment]
@TanninOne Someone responded to me in the Qt support page i linked saying that QTDeclarative plugin has been removed in Qt5.6. So i think its time to update your modorganizer project.

**Comment by LePresidente** [comment]
Hi, 

Ok so there have been a few changes since @TanninOne left this.

The master branch is for the newer QT versions that will require QTWebEngine. Everything compiles and runs though there are a few newer bugs like the Mod window doesn't show info anymore from the nexus webpages but it works.

The MSVC2013 branch is the last branch i used to release 2.0.8.3b that still uses QT5.5.

Now I have tested this recently and currently this compiles everything from start to finish just fine. 

The error "building usvfs 32bit dll failed" is a little unhelpful though the line above that is what is required to help you debug. 

That line is spawned by unimake to build the 32bit DLL using the folllowing  command 

unimake.py -d "{output directory from parent command}" --set architecture="x86" -b "build_32" -p "progress_32" -i "install_32" usvfs

You will need to let me know which project failed and upload the stderr.log and stdout.log file from the relevant project folder.

e.g if you saw "boost shared failed" then "building usvfs 32bit dll failed" you will upload the files from "E:\MO2\build_32\boost_1_64_0"

Then I will help you debug, I'll also be lurking on the discord channel.
